services:
  dialoguefinder:
    build:
      context: .
    container_name: DialogueFinder
    environment:
      - ELASTIC_HOSTNAME=Elasticsearch_DF
      - ELASTIC_SCHEME # Optional
      - ELASTIC_PORT # Optional
      - ELASTIC_PASSWORD # Optional
      - MEDIA_PATH # Optional
    volumes:
      - ${VOL_MEDIA_PATH}:/mnt/media
    ports:
      - "8080:8080"
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --spider http://localhost:8080 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - dialoguefinder
  elasticsearch:
    image: elasticsearch:8.17.0
    container_name: Elasticsearch_DF
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -k --silent --fail http://localhost:9200/_cluster/health || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 15
    networks:
      - dialoguefinder
networks:
  dialoguefinder:
    driver: bridge